# NEOS DEVELOPMENT ENVIRONMENT
#
# For instructions how to use docker-compose, see
# https://docs.neos.io/cms/installation-development-setup/docker-and-docker-compose-setup#docker-compose-cheat-sheet
version: '3.5'
services:
  # Neos CMS
  neos:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      FLOW_CONTEXT: 'Production'
      FLOW_HTTP_TRUSTED_PROXIES: '*'
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./:/var/www
    networks:
      - internal-network

  web:
    image: nginx:alpine
    container_name: web
    restart: always
    tty: true
    environment:
      VIRTUAL_HOST: INSERT_HOST_HERER
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: INSERT_HOST_HERER
      LETSENCRYPT_EMAIL: admin@fleigm.de
    expose:
      - 80
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - internal-network
      - nginx-proxy

  # DB
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'db'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - internal-network

volumes:
  db:

#Docker Networks
networks:
  internal-network:
    driver: bridge
  nginx-proxy:
    external: true
    name: nginx-proxy
