
Carbon:
  IncludeAssets:
    Packages:
      aa_Theme:
        Path:
          Inline:
            CSS: 'Public/Frontend/dist'
            JS: 'Public/Frontend/dist'
          File:
            CSS: 'Public/Frontend/dist'
            JS: 'Public/Frontend/dist'
        # Asset files who get's loaded in live and backend view
        General:
          Head:
            - main.css
          Body:
            - main.js
